#
# Copyright (C) 2020 Grakn Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

build:
  correctness:
    build:
      machine: graknlabs-ubuntu-20.04
      script: |
        bazel build --config=rbe //...
        bazel run @graknlabs_dependencies//tool/checkstyle:test-coverage
        bazel test --config=rbe $(bazel query 'kind(checkstyle_test, //...)')
    build-dependency:
      machine: graknlabs-ubuntu-20.04
      script: |
        dependencies/maven/update.sh
        git diff --exit-code dependencies/maven/artifacts.snapshot
        bazel run @graknlabs_dependencies//tool/unuseddeps:unused-deps -- list
    test-client:
      machine: graknlabs-ubuntu-20.04
      script: |
        bazel test --config=rbe //client/test --test_output=errors
    deploy-maven-snapshot:
      filter:
        owner: graknlabs
        branch: master
      machine: graknlabs-ubuntu-20.04
      script: |
        export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(git rev-parse HEAD) //client:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //protocol:deploy-maven -- snapshot
      dependencies: [build, build-dependency, test-client]
    test-deployment-maven:
      filter:
        owner: graknlabs
        branch: master
      machine: graknlabs-ubuntu-20.04
      script: |
        sed -i -e "s/GRABL_TRACING_VERSION_MARKER/$(git rev-parse HEAD)/g" test/deployment/pom.xml
        cat test/deployment/pom.xml
        cd test/deployment && mvn test
      dependencies: [deploy-maven-snapshot]

release:
  filter:
    owner: graknlabs
    branch: master
  validation:
    validate-dependencies:
      machine: graknlabs-ubuntu-20.04
      script: bazel test //:release-validate-deps --test_output=streamed
  deployment:
    deploy-github:
      machine: graknlabs-ubuntu-20.04
      script: |
        pip install certifi
        export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @graknlabs_dependencies//tool/release:create-notes -- grabl-tracing $(cat VERSION) ./RELEASE_TEMPLATE.md
        export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
        bazel run --define version=$(cat VERSION) //:deploy-github -- $GRABL_COMMIT
    deploy-maven-release:
      machine: graknlabs-ubuntu-20.04
      script: |
        export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(cat VERSION) //protocol:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //client:deploy-maven -- release
      dependencies: [deploy-github]
